### ISSUE TITLE
marshmallow.exceptions.ValidationError: {'id': ['Unknown field.']}

### ISSUE THREAD

**Issue by NAN-CForadas** [klen/marshmallow-peewee#121]
# The Output/Traceback

```
1
{'active': True,
 'created': '2022-06-02T21:04:07.061651',
 'id': '1',
 'name': 'Mike',
 'rating': 0,
 'role': '1',
 'title': None}
Traceback (most recent call last):
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/app.py", line 49, in <module>
    result = UserSchema().load(result)
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/venv/lib/python3.10/site-packages/marshmallow_peewee/schema.py", line 90, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'id': ['Unknown field.']}

Process finished with exit code 1
```

# Python Version

```
'3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]'
```
# Library Versions

```
marshmallow==3.16.0
Marshmallow-Peewee==3.2.1
peewee==3.14.10
```

# Code

```python

1. import pprint
2. 
3. import peewee as pw
4. from peewee import SqliteDatabase
5. from marshmallow_peewee import ModelSchema
6. from marshmallow_peewee import Related
7. import datetime as dt
8. 
9. db = SqliteDatabase(':memory:')
10. 
11. 
12. class Role(pw.Model):
13.     name = pw.CharField(255, default='user')
14. 
15.     class Meta:
16.         database = db # This model uses the "people.db" database.
17. 
18. 
19. class User(pw.Model):
20.     created = pw.DateTimeField(default=dt.datetime.now())
21.     name = pw.CharField(255)
22.     title = pw.CharField(127, null=True)
23.     active = pw.BooleanField(default=True)
24.     rating = pw.IntegerField(default=0)
25.     role = pw.ForeignKeyField(Role)
26. 
27.     class Meta:
28.         database = db # This model uses the "people.db" database.
29. 
30. 
31. class UserSchema(ModelSchema):
32.     class Meta:
33.         model = User
34. 
35. 
36. # create the tables
37. db.create_tables([Role, User])
38. 
39. # create role
40. role = Role.create()
41. print(role)
42. 
43. # create a user
44. user = User.create(name='Mike', role=role.id)
45. 
46. result = UserSchema().dump(user)
47. pprint.pprint(result)
48. 
49. result = UserSchema().load(result)
50. assert isinstance(result, User)
51. assert result.name == 'Mike'
52. 
53. 
54. class UserSchema(ModelSchema):
55.     role = Related()
56. 
57.     class Meta:
58.         model = User
59. 
60. 
61. result = UserSchema().dump(user)
62. print(result)
63. 
64. result = UserSchema().load(result)
65. assert isinstance(result, User)
66. assert isinstance(result.role, Role)
67. 
```

# Comments

I happend to notice that the **results**  'id' is a string and not an integer unlike in your example code (quickstart).

**Comment by NAN-CForadas** [comment]
Found fix in #55.  Closing issue.

**Comment by NAN-CForadas** [comment]
Made Change,

```python

1. import pprint
2. 
3. import peewee as pw
4. from peewee import SqliteDatabase
5. from marshmallow_peewee import ModelSchema
6. from marshmallow_peewee import Related
7. import datetime as dt
8. 
9. db = SqliteDatabase(':memory:')
10. 
11. 
12. class Role(pw.Model):
13.     name = pw.CharField(255, default='user')
14. 
15.     class Meta:
16.         database = db # This model uses the "people.db" database.
17. 
18. 
19. class User(pw.Model):
20.     created = pw.DateTimeField(default=dt.datetime.now())
21.     name = pw.CharField(255)
22.     title = pw.CharField(127, null=True)
23.     active = pw.BooleanField(default=True)
24.     rating = pw.IntegerField(default=0)
25.     role = pw.ForeignKeyField(Role)
26. 
27.     class Meta:
28.         database = db # This model uses the "people.db" database.
29. 
30. 
31. class UserSchema(ModelSchema):
32.     class Meta:
33.         model = User
34.         string_keys = False
35. 
36. 
37. # create the tables
38. db.create_tables([Role, User])
39. 
40. # create role
41. role = Role.create()
42. print(role)
43. 
44. # create a user
45. user = User.create(name='Mike', role=role.id)
46. 
47. result = UserSchema().dump(user)
48. pprint.pprint(result)
49. 
50. result = UserSchema().load(result)
51. assert isinstance(result, User)
52. assert result.name == 'Mike'
53. 
54. 
55. class UserSchema(ModelSchema):
56.     role = Related()
57. 
58.     class Meta:
59.         model = User
60.         string_keys = False
61. 
62. result = UserSchema().dump(user)
63. print(result)
64. 
65. result = UserSchema().load(result)
66. assert isinstance(result, User)
67. assert isinstance(result.role, Role)
68. ```

still getting error

1
{'active': True,
 'created': '2022-06-02T21:17:43.408897',
 'id': 1,
 'name': 'Mike',
 'rating': 0,
 'role': 1,
 'title': None}
Traceback (most recent call last):
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/app.py", line 50, in <module>
    result = UserSchema().load(result)
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/venv/lib/python3.10/site-packages/marshmallow_peewee/schema.py", line 90, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/Users/cforadas/PycharmProjects/flask_blueprint_testing/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'id': ['Unknown field.']}

Process finished with exit code 1

**Comment by klen** [comment]
Peewee-Marshmallow by default generate `id` field dump only. So marshmallow raises an error when you are trying to send `id`. You may set `Meta.unknown = 'IGNORE` or `Meta.dump_only_pk = False`
